# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G8zRoyZTKsYSrlSELDbiPpAX8F74QAMh
"""

import streamlit as st
import imageio.v3 as iio
from PIL import Image
import io

# --- Page Configuration ---
st.set_page_config(
    page_title="GIF Creator",
    page_icon="✨"
)

# --- App UI ---
st.title("Simple GIF Creator 🖼️")
st.info("Instructions: Upload two images below (PNG or JPG). A GIF will be generated which you can then preview and download.")

# Use columns to place uploaders side-by-side
col1, col2 = st.columns(2)

with col1:
    st.subheader("Image 1")
    uploaded_file1 = st.file_uploader("Upload the first image", type=['png', 'jpg', 'jpeg'], key="uploader1")

with col2:
    st.subheader("Image 2")
    uploaded_file2 = st.file_uploader("Upload the second image", type=['png', 'jpg', 'jpeg'], key="uploader2")

# --- GIF Generation and Download Logic ---
if uploaded_file1 is not None and uploaded_file2 is not None:
    # Read the uploaded image files using Pillow
    image1 = Image.open(uploaded_file1)
    image2 = Image.open(uploaded_file2)

    images = [image1, image2]

    # Create an in-memory byte stream to hold the GIF
    gif_bytes = io.BytesIO()

    # Save the images as a GIF to the byte stream
    iio.imwrite(gif_bytes, images, format='GIF', duration=0.5, loop=0)

    gif_bytes.seek(0)

    st.subheader("Your Generated GIF")
    st.image(gif_bytes, caption='Your awesome GIF!')

    # Provide a download button for the GIF
    st.download_button(
        label="Download GIF",
        data=gif_bytes,
        file_name="generated_gif.gif",
        mime="image/gif"
    )
else:
    st.warning("Please upload both images to generate the GIF.")